#name: Push to develop
#
#on:
#  push:
#    branches:
#      - develop
#
#jobs:
#  deploy-storybook:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          submodules: recursive
#      - name: Use Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: '14.x'
#      - name: Install dependencies
#        run: yarn
#      - name: Deploy storybook to GitHub Pages
#        run: |
#          cat <<EOF >".env"
#            VITE_HPOS_PORT: 4567
#          EOF
#          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
#          yarn deploy-storybook
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
