export const categories = [
  'Adult',
  'Not-For-Profit',
  'Books',
  'Medical',
  'Business',
  'Music',
  'Developer Tools',
  'Crypto',
  'Navigation',
  'Education',
  'News',
  'Entertainment',
  'Photo & Video',
  'Finance',
  'FinTech',
  'Productivity',
  'Food & Drink',
  'Reference',
  'Games',
  'Gaming',
  'Gambling',
  'Graphics & Design',
  'Shopping',
  'Health & Fitness',
  'Social Networking',
  'Lifestyle',
  'Sports',
  'Kids',
  'Travel',
  'Magazines & Newspapers',
  'Utilities',
  'Weather',
  'Open-Source'
]
