export const categories = [
  'Academic publication',
  'Adult',
  'Books',
  'Business',
  'Crypto',
  'Developer Tools',
  'Education',
  'Entertainment',
  'Finance',
  'FinTech',
  'Fitness',
  'Food & Drink',
  'Gambling',
  'Games',
  'Graphics & Design',
  'Health & Wellbeing',
  'Kids',
  'Lifestyle',
  'Medical',
  'Music',
  'News',
  'Not-For-Profit',
  'Open-Source',
  'Photo & Video',
  'Productivity',
  'Reference',
  'Shopping',
  'Social Networking',
  'Sports',
  'Travel',
  'TV & Movies',
  'Utilities',
  'Weather',
  'Wedding'
]
